/* Criação de tipos ENUM */
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_cnh') THEN
    CREATE TYPE status_cnh AS ENUM ('Válida', 'Vencida', 'Suspensa');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'cargo') THEN
    CREATE TYPE cargo AS ENUM ('Fiscal', 'Motorista', 'Cobrador');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'grau') THEN
    CREATE TYPE grau AS ENUM ('Leve', 'Moderado', 'Grave');
  END IF;
END$$;

/* Criação de tabelas */
CREATE TABLE IF NOT EXISTS Local (
  lat float NOT NULL,
  lng float NOT NULL,
  nome varchar,
  descricao varchar,
  PRIMARY KEY (lat, lng)
);

CREATE TABLE IF NOT EXISTS Empresa (
  cnpj char(14) PRIMARY KEY,
  razao_social varchar NOT NULL,
  nome_fantasia varchar,
  lat_local float NOT NULL,
  lng_local float NOT NULL,
  FOREIGN KEY (lat_local, lng_local) REFERENCES Local (lat, lng) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Funcionario (
  cnpj_empresa char(14) NOT NULL,
  codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  sexo varchar,
  cargo cargo NOT NULL,
  data_nascimento date,
  data_contratacao date NOT NULL,
  data_demissao date,
  FOREIGN KEY (cnpj_empresa) REFERENCES Empresa (cnpj) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Telefone_Funcionario (
  codigo_func bigint NOT NULL,
  telefone varchar(12) UNIQUE,
  PRIMARY KEY (codigo_func, telefone),
  FOREIGN KEY (codigo_func) REFERENCES Funcionario (codigo)
);

CREATE TABLE IF NOT EXISTS Motorista (
  cnh char(9) PRIMARY KEY,
  codigo_funcionario bigint NOT NULL UNIQUE,
  status_cnh status_cnh NOT NULL,
  data_validade_cnh date NOT NULL, 
  FOREIGN KEY (codigo_funcionario) REFERENCES Funcionario (codigo) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Categoria (
  codigo int PRIMARY KEY,
  nome varchar UNIQUE NOT NULL,
  descricao varchar
);

CREATE TABLE IF NOT EXISTS Modelo (
  codigo int PRIMARY KEY,
  codigo_categoria int NOT NULL,
  nome varchar UNIQUE NOT NULL,
  FOREIGN KEY (codigo_categoria) REFERENCES Categoria (codigo)
);

CREATE TABLE IF NOT EXISTS Veiculo (
  placa char(7) PRIMARY KEY,
  cnpj_empresa char(14) NOT NULL,
  codigo_modelo int NOT NULL,
  km float,
  ano_fabricacao int,
  FOREIGN KEY (cnpj_empresa) REFERENCES Empresa (cnpj),
  FOREIGN KEY (codigo_modelo) REFERENCES Modelo (codigo)
);

CREATE TABLE IF NOT EXISTS Manutencao (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  placa_veiculo char(7) NOT NULL,
  data_hora timestamp NOT NULL,
  FOREIGN KEY (placa_veiculo) REFERENCES Veiculo (placa) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Servico (
  codigo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao varchar NOT NULL,
  valor float NOT NULL
);

CREATE TABLE IF NOT EXISTS Manutencao_Servico (
  id_manutencao int NOT NULL,
  codigo_servico int NOT NULL,
  PRIMARY KEY (id_manutencao, codigo_servico),
  FOREIGN KEY (id_manutencao) REFERENCES Manutencao (id) ON DELETE CASCADE,
  FOREIGN KEY (codigo_servico) REFERENCES Servico (codigo)
);

CREATE TABLE IF NOT EXISTS Ocorrencia (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  placa_veiculo char(7) NOT NULL,
  data_hora timestamp NOT NULL,
  lat_local float NOT NULL,
  lng_local float NOT NULL,
  FOREIGN KEY (placa_veiculo) REFERENCES Veiculo (placa) ON DELETE CASCADE,
  FOREIGN KEY (lat_local, lng_local) REFERENCES Local (lat, lng)
);

CREATE TABLE IF NOT EXISTS Acidente (
  id_ocorrencia int PRIMARY KEY,
  descricao varchar,
  gravidade grau NOT NULL,
  numero_feridos int,
  numero_mortos int,
  FOREIGN KEY (id_ocorrencia) REFERENCES Ocorrencia (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Avaria (
  id_ocorrencia int PRIMARY KEY,
  descricao varchar,
  nivel_dano grau NOT NULL,
  total bool DEFAULT FALSE,
  FOREIGN KEY (id_ocorrencia) REFERENCES Ocorrencia (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Linha (
  cnpj_empresa char(14) NOT NULL,
  codigo varchar(5) PRIMARY KEY,
  FOREIGN KEY (cnpj_empresa) REFERENCES Empresa (cnpj) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Itinerario (
  codigo_linha varchar(5) NOT NULL,
  lat_local float NOT NULL,
  lng_local float NOT NULL,
  numero int NOT NULL,
  PRIMARY KEY (codigo_linha, lat_local, lng_local, numero),
  FOREIGN KEY (codigo_linha) REFERENCES Linha (codigo) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (lat_local, lng_local) REFERENCES Local (lat, lng) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Viagem (
  codigo_linha varchar(5) NOT NULL,
  codigo_cobrador bigint NOT NULL,
  codigo_motorista bigint NOT NULL,
  placa_veiculo char(7) NOT NULL,
  data date NOT NULL,
  hora_partida timestamp NOT NULL,
  hora_chegada timestamp,
  PRIMARY KEY (
    codigo_linha,
    codigo_cobrador,
    codigo_motorista,
    placa_veiculo,
    data,
    hora_partida
  ),
  FOREIGN KEY (codigo_linha) REFERENCES Linha (codigo) ON DELETE CASCADE,
  FOREIGN KEY (codigo_cobrador) REFERENCES Funcionario (codigo) ON DELETE CASCADE,
  FOREIGN KEY (codigo_motorista) REFERENCES Funcionario (codigo) ON DELETE CASCADE,
  FOREIGN KEY (placa_veiculo) REFERENCES Veiculo (placa) ON DELETE CASCADE
);


/* Criação de triggers e funções auxiliares */

-- Função para checar se o cargo de um funcionário é igual ao cargo esperado
CREATE OR REPLACE FUNCTION checkFuncRole (func_id BIGINT, expected_role cargo) RETURNS BOOLEAN AS $$
DECLARE
    actual_role cargo;
BEGIN
    SELECT cargo INTO actual_role
    FROM Funcionario
    WHERE codigo = func_id;

    IF NOT FOUND THEN
      RETURN FALSE;
    END IF;

    RETURN actual_role = expected_role;
END;
$$ LANGUAGE plpgsql;

-- Trigger function para bloquear operações INSERT inválidas
CREATE OR REPLACE FUNCTION prevent_invalid_insert()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_TABLE_NAME = 'motorista' THEN
    IF NOT checkFuncRole(NEW.codigo_funcionario, 'Motorista') THEN
      RAISE EXCEPTION 'Operação inválida: Funcionário de código % não possui cargo "Motorista"', NEW.codigo_funcionario;
    END IF;
  END IF;
  
  IF TG_TABLE_NAME = 'viagem' THEN
    IF NOT checkFuncRole(NEW.codigo_cobrador, 'Cobrador') THEN
      RAISE EXCEPTION 'Operação inválida: Funcionário de código % não possui cargo "Cobrador"', NEW.codigo_cobrador;
    END IF;
    IF NOT checkFuncRole(NEW.codigo_motorista, 'Motorista') THEN
      RAISE EXCEPTION 'Operação inválida: Funcionário de código % não possui cargo "Motorista"', NEW.codigo_motorista;
    END IF;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para checar se um motorista possui o cargo "Motorista"
CREATE OR REPLACE TRIGGER block_invalid_driver_insert 
  BEFORE INSERT ON Motorista
  FOR EACH ROW
  EXECUTE FUNCTION prevent_invalid_insert();

-- Trigger para checar se o cobrador e o motorista de uma viagem possuem os cargos
-- correspondentes
CREATE OR REPLACE TRIGGER block_invalid_travel_insert 
  BEFORE INSERT ON Viagem
  FOR EACH ROW
  EXECUTE FUNCTION prevent_invalid_insert();
  